INCIDENT_TYPES = (('THEFT', 'Roubo'),
                  ('ASSAULT', 'Assalto'),
                  ('VANDALISM', 'Vandalismo'),
                  ('ROBBERY', 'Roubo à mão armada'),
                  ('BURGLARY', 'Arrombamento'),
                  ('FRAUD', 'Fraude'),
                  ('HARASSMENT', 'Assédio'),
                  ('DRUG_OFFENSE', 'Delito de drogas'),
                  ('DOMESTIC_VIOLENCE', 'Violência doméstica'),
                  ('PROPERTY_DAMAGE', 'Danos à propriedade')),
