# Generated by Django 5.0.3 on 2024-03-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0011_alter_person_person_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('leaders', models.ManyToManyField(blank=True, to='persons.person')),
            ],
        ),
    ]
