# Generated by Django 5.0.3 on 2024-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_management', '0002_faction_member_alter_faction_leaders'),
        ('persons', '0013_remove_person_faction_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='leaders', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='member',
            field=models.ManyToManyField(related_name='members', to='persons.person'),
        ),
    ]
