# Generated by Django 5.0.3 on 2024-03-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_management', '0003_alter_faction_leaders_alter_faction_member'),
        ('persons', '0013_remove_person_faction_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='members', to='persons.person'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('reported_at', models.DateField(blank=True)),
                ('involved', models.ManyToManyField(blank=True, related_name='involved_persons', to='persons.person')),
                ('person_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident', to='persons.person')),
            ],
        ),
    ]
