# Generated by Django 5.0.3 on 2024-03-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_management', '0004_alter_faction_member_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
