# Generated by Django 5.0.3 on 2024-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_management', '0005_incident_details_alter_incident_reported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(blank=True, choices=[('THEFT', 'Roubo'), ('ASSAULT', 'Assalto'), ('VANDALISM', 'Vandalismo'), ('ROBBERY', 'Roubo à mão armada'), ('BURGLARY', 'Arrombamento'), ('FRAUD', 'Fraude'), ('HARASSMENT', 'Assédio'), ('DRUG_OFFENSE', 'Delito de drogas'), ('DOMESTIC_VIOLENCE', 'Violência doméstica'), ('PROPERTY_DAMAGE', 'Danos à propriedade')], max_length=100, null=True),
        ),
    ]
