# Generated by Django 5.0.3 on 2024-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_management', '0006_incident_type_incident'),
        ('persons', '0020_alter_relationship_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='leaders', to='persons.person', verbose_name='Líderes'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='members', to='persons.person', verbose_name='Membros'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da ocorrência'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='involved',
            field=models.ManyToManyField(blank=True, related_name='involved_persons', to='persons.person', verbose_name='Pessoas envolvidas'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data da ocorrência'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(blank=True, choices=[('THEFT', 'Roubo'), ('ASSAULT', 'Assalto'), ('VANDALISM', 'Vandalismo'), ('ROBBERY', 'Roubo à mão armada'), ('BURGLARY', 'Arrombamento'), ('FRAUD', 'Fraude'), ('HARASSMENT', 'Assédio'), ('DRUG_OFFENSE', 'Delito de drogas'), ('DOMESTIC_VIOLENCE', 'Violência doméstica'), ('PROPERTY_DAMAGE', 'Danos à propriedade')], max_length=100, null=True, verbose_name='Tipo de ocorrência'),
        ),
    ]
