# Generated by Django 5.0.3 on 2024-03-21 20:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='number_register',
            field=models.UUIDField(default=uuid.uuid1, unique=True),
        ),
    ]
