# Generated by Django 5.0.3 on 2024-03-21 20:58

import persons.persons_validator
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_number_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11, null=True, validators=[persons.persons_validator.validator_cpf]),
        ),
        migrations.AlterField(
            model_name='person',
            name='number_register',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
