# Generated by Django 5.0.3 on 2024-03-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_address_person_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_relation', models.CharField(choices=[('SIBLINGS', 'Irmãos'), ('FATHER', 'Pai'), ('MOTHER', 'Mãe'), ('GRANDPARENTS', 'Avôs/Avós'), ('AUNT_UNCLE', 'Tios/Tias'), ('COUSIN', 'Primo/Prima'), ('NEPHEW_NIECE', 'Sobrinho/Sobrinhao'), ('GODPARENTS', 'Padrinhos/Madrinhaso'), ('FRIEND', 'Amigo'), ('COLLEAGUE', 'Colega de trabalho'), ('PARTNER', 'Parceiro/Parceira'), ('HUSBAND_WIFE', 'Esposo/Esposa'), ('CHILD', 'Filho/Filha')], max_length=30)),
                ('observation', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(limit_choices_to=models.Q(('id', models.F('person_id'))), on_delete=django.db.models.deletion.PROTECT, related_name='relationship', to='persons.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='person_relations',
            field=models.ManyToManyField(related_name='persons_relations', to='persons.relationship'),
        ),
    ]
