# Generated by Django 5.0.3 on 2024-03-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_relationship_person_person_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_relations',
            field=models.ManyToManyField(related_name='person_relationships', to='persons.relationship'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person',
            field=models.ForeignKey(limit_choices_to=models.Q(('id', models.F('person_id'))), on_delete=django.db.models.deletion.PROTECT, related_name='person_relation', to='persons.person'),
        ),
    ]
