# Generated by Django 5.0.3 on 2024-03-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_alter_relationship_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
