# Generated by Django 5.0.3 on 2024-03-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal_management', '0001_initial'),
        ('persons', '0011_alter_person_person_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='faction_relations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='criminal_management.faction'),
        ),
    ]
