# Generated by Django 5.0.3 on 2024-03-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_person_faction_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='faction_relations',
        ),
    ]
