# Generated by Django 5.0.3 on 2024-03-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_person_date_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
