# Generated by Django 5.0.3 on 2024-03-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_person_nickname_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='persons.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
