# Generated by Django 5.0.3 on 2024-03-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_alter_person_address_alter_person_date_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='distric',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='address',
            name='reference_point',
            field=models.TextField(blank=True, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_relation', to='persons.person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type_relation',
            field=models.CharField(choices=[('SIBLINGS', 'Irmãos'), ('FATHER', 'Pai'), ('MOTHER', 'Mãe'), ('GRANDPARENTS', 'Avôs/Avós'), ('AUNT_UNCLE', 'Tios/Tias'), ('COUSIN', 'Primo/Prima'), ('NEPHEW_NIECE', 'Sobrinho/Sobrinhao'), ('GODPARENTS', 'Padrinhos/Madrinhaso'), ('FRIEND', 'Amigo'), ('COLLEAGUE', 'Colega de trabalho'), ('PARTNER', 'Parceiro/Parceira'), ('HUSBAND_WIFE', 'Esposo/Esposa'), ('CHILD', 'Filho/Filha')], max_length=30, verbose_name='Tipo da relação'),
        ),
    ]
